[NEW SOURCE] Add support for gmanga | resolve #5

diff --git a/release/standalone/mangadl b/release/standalone/mangadl
--- a/release/standalone/mangadl
+++ b/release/standalone/mangadl
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 SELF_SOURCE="true"
-ALL_SOURCES=("fanfox" "manga4life" "mangafox" "mangahub" "mangakakalot" "manganelo" "readmanhwa" )
+ALL_SOURCES=("fanfox" "gmanga" "manga4life" "mangafox" "mangahub" "mangakakalot" "manganelo" "readmanhwa" )
 _basename(){
 declare tmp
 tmp=${1%"${1##*[!/]}"}
@@ -359,12 +359,87 @@ done
 fi
 _clear_line 1
 shopt -s extglob
-mapfile -t IMAGES <<<"$(_tmp="$(printf "%s/*+(jpg|png)\n" "${PAGES[@]}")"&&printf "%b\n" $_tmp)"
+mapfile -t IMAGES <<<"$(_tmp="$(printf "%s/*+(jpg|png|webp)\n" "${PAGES[@]}")"&&printf "%b\n" $_tmp)"
 TOTAL_IMAGES_SIZE="$(: "$(wc -c "${IMAGES[@]}"|_tail 1|grep -Eo '[0-9]'+)"
 printf "%s\n" "$(_bytes_to_human "$_")")"
 export TOTAL_IMAGES_SIZE IMAGES
 shopt -u extglob
 return 0
+}
+_search_manga_gmanga(){
+declare input="$1" num_of_search="$2" post_data search_json
+post_data="$(jq -n --arg q "$input" '{query: $q, includes:["Manga"]}')"
+search_json="$(curl -# --compressed https://gmanga.org/api/quick_search \
+-d "$post_data" \
+-e "gmanga.org" -H "Content-Type: application/json")"
+[[ $search_json =~ \"data\":*\[\] ]]&&return 1
+declare manga_info&&declare -g NAMES TOTAL_SEARCHES SLUGS
+mapfile -t NAMES <<<"$(jq '.[].data[].title' -r <<<"$search_json")"
+mapfile -t manga_info <<<"$(jq '.[].data[].id,.[].data[].latest_chapter,.[].data[].story_status' -r <<<"$search_json")"
+TOTAL_SEARCHES="${#NAMES[@]}"
+i=1
+for name in "${NAMES[@]}";do
+num="$((i++))"
+[[ $num -gt $num_of_search ]]&&break
+num_id="$((num-1))" id="${manga_info[$num_id]//null/Unknown}" SLUGS+=("$id")
+num_latest="$((num_id+TOTAL_SEARCHES))" latest="${manga_info[$num_latest]//null/Unknown}"
+num_status="$((num_latest+TOTAL_SEARCHES))" status="${manga_info[$num_status]//null/Unknown}"&&case "$status" in
+2)status="Ongoing";;
+3)status="Completed";;
+*)status="Unknown"
+esac
+OPTION_NAMES+=("$num. $name
+   URL: https://gmanga.org/mangas/$id
+   Latest: $latest
+   Status: $status")
+done
+export TOTAL_SEARCHES NAMES SLUGS OPTION_NAMES
+}
+_set_manga_variables_gmanga(){
+declare option="$1"
+SLUG="${SLUGS[$((option-1))]}"
+NAME="${NAMES[$((option-1))]}"
+export SLUG NAME
+}
+_fetch_manga_details_gmanga(){
+declare slug="${1:-$SLUG}" fetch_name="${2:-}" json
+slug="$(_basename "$slug")"
+json="$(curl -L -# --compressed "https://gmanga.org/api/mangas/$slug")"
+_clear_line 1
+case "$json" in
+*'"mangaData":null'*|*'"error":"Internal Server Error"'*)return 1
+esac
+[[ -n $fetch_name ]]&&NAME="$(jq '.mangaData.title' -r <<<"$json")"
+_print_center "justify" "Retrieving manga" " chapters.." "-"
+declare enc_json enc_data dec_data dec_json key iv
+enc_json="$(curl -# -L --compressed "https://gmanga.org/api/mangas/$slug/releases")"&&_clear_line 1
+enc_data="$(: "$(jq -re '.data' <<<"$enc_json")"&&printf '%s' "${_//|/$'\n'}")"||return 1
+dec_data="$(sed -n 1p <<<"$enc_data")"
+key="$(sed -n 4p <<<"$enc_data")"&&key="$(openssl sha256 <<<"$key")"&&key="${key//* /}"
+iv="$(sed -n 3p <<<"$enc_data")"&&iv="$(openssl base64 -A -d <<<"$iv"|od -A n -t x1)"&&iv="${iv//$'\n'/}"&&iv="${iv// /}"
+dec_json="$(openssl aes-256-cbc -d -K "$key" -iv "$iv" -in <(openssl base64 -A -d <<<"$dec_data") -out -)" 2>|/dev/null||return 1
+mapfile -t PAGES <<<"$(jq '.rows[2].rows[][1]' -re <<<"$dec_json"|sort -V)"||return 1
+_clear_line 1
+export SLUG="$slug" PAGES REFERER="gmanga.org"
+}
+_download_chapter_gmanga(){
+curl -s -L --compressed "https://gmanga.org/mangas/$SLUG/$NAME/${page:-?}/" -w "\n%{http_code}\n"
+}
+_count_images_gmanga(){
+TOTAL_IMAGES="$(: "$(for page in "${PAGES[@]}";do
+{
+json="$(grep 'class="js-react-on-rails-component"' "$page/$page"_chapter|grep -oE '\{.*\}')"||:
+extra_string="_webp"
+images="$(jq '.readerDataAction.readerData.release.webp_pages[]' -re <<<"$json")"||{
+images="$(jq '.readerDataAction.readerData.release.pages[]' -re <<<"$json")"
+extra_string=""
+}
+release="$(jq '.readerDataAction.readerData.release.storage_key' -r <<<"$json")"
+printf '%s\n' "$images"|sed "s|^|https://media.$REFERER/uploads/releases/$release/mq$extra_string/|g" >|"$page/$page"_images
+_count <"$page/$page"_images
+}&
+done)"&&printf "%s\n" "$((${_//$'\n'/ + }))")"
+export TOTAL_IMAGES
 }
 _search_manga_manga4life(){
 declare file_path="$HOME/.manga4life.list"
@@ -918,7 +993,11 @@ _source_manga_util(){
 SOURCE="${1:-$SOURCE}"
 case "$SOURCE" in
 *mangakakalot*)SOURCE="manganelo";;
-*fanfox*)SOURCE="mangafox"
+*fanfox*)SOURCE="mangafox";;
+*gmanga*)for c in jq openssl od
+do
+command -v "$c" >|/dev/null||{ printf "%s\n" "Install $c to use gmanga"&&return 1;}
+done
 esac
 [[ -z $SELF_SOURCE ]]&&{
 utils_file="$UTILS_FOLDER/$SOURCE-scraper.bash"
@@ -933,7 +1012,7 @@ return 0
 }
 _process_arguments(){
 declare input utils_file _exit
-_source_manga_util
+_source_manga_util||return 1
 CURRENT_DIR="$PWD"
 { [[ -n $FOLDER ]]&&mkdir -p "$FOLDER"&&{ cd "${FOLDER:-.}"||exit 1;};}||:
 declare -A Aseen
@@ -1033,7 +1112,7 @@ export DECREASE_QUALITY CONVERT_DIR
 { mkdir -p "$CONVERT_DIR"&&cd "$CONVERT_DIR"&&mkdir -p "${PAGES[@]}"&&cd - &>/dev/null;}||exit 1
 _convert_page(){
 declare page="${1:?}" copy images image current_quality new_quality
-mapfile -t images <<<"$(printf "%b\n%b\n" "$page/"*jpg "$page/"*png|grep -vE '\*png|\*jpg')"
+mapfile -t images <<<"$(printf "%b\n%b\n" "$page/"*jpg "$page/"*png "$page/"*webp|grep -vE '\*png|\*jpg|\*webp')"
 image="${images[0]}"
 current_quality="$(identify -format %Q "$image")"
 new_quality="$((DECREASE_QUALITY<current_quality?(current_quality-DECREASE_QUALITY):current_quality))"
